# Author: Suman Somaiah B A (original placeholder)
# --- Owner: (assign, see docs/TEAM_SPLIT.md) | Streamlit UI, usage cap, secrets, error display ---
# AI-assisted: drafted with Claude Code. The owner must review it and be able to explain it (IS883 §9).
import streamlit as st

from leasecheck import config, prompts
from leasecheck.analyzer import analyze, findings_digest
from leasecheck.llm import GeminiLLM, LLMError
from leasecheck.parsing import InputRejected
from leasecheck.retrieval import SourceIndex, format_passages

st.set_page_config(page_title="Boston Lease Checker", page_icon="🏠", layout="wide")

DISCLAIMER = (
    "**This is not legal advice.** The results are generated by a language model and may be wrong or "
    "incomplete. \"No issue found\" does **not** mean a clause is legal. Before signing, check anything "
    "important with a lawyer or a tenant-rights organisation."
)

LABEL_STYLE = {
    "possibly_unlawful": ("🔴", "Possibly unlawful"),
    "unusual": ("🟡", "Unusual: ask about it"),
    "lawful": ("🟢", "No issue found"),
    "not_checked": ("⚪", "Could not be checked"),
}
STATUS_STYLE = {"ok": "🟢 Allowed", "check": "🟡 Check", "not_allowed": "🔴 Not allowed"}


# ---------- setup: secrets, client, source index (cached across sessions) ----------

def get_api_key() -> str | None:
    try:
        return st.secrets["GEMINI_API_KEY"]
    except Exception:  # no secrets file, or the key is not in it
        return None


@st.cache_resource(show_spinner="Loading Massachusetts law sources...")
def get_index(api_key: str) -> SourceIndex:
    return SourceIndex.build(GeminiLLM(api_key))


def init_state() -> None:
    defaults = {"analyses_used": 0, "chat_used": 0, "result": None, "filename": None, "chat": [], "llm": None}
    for key, value in defaults.items():
        st.session_state.setdefault(key, value)


init_state()
api_key = get_api_key()

st.title("🏠 Boston Lease Checker")
st.caption("For students signing a Greater Boston apartment lease: find clauses that may break "
           "Massachusetts tenant law, with the law they may break.")
st.warning(DISCLAIMER)

if not api_key:
    st.error("The app is not configured: GEMINI_API_KEY is missing from Streamlit secrets.")
    st.stop()

if st.session_state.llm is None:
    st.session_state.llm = GeminiLLM(api_key)
llm: GeminiLLM = st.session_state.llm

with st.sidebar:
    st.subheader("Your session")
    left = config.MAX_ANALYSES_PER_SESSION - st.session_state.analyses_used
    st.write(f"Lease checks left: **{left}** of {config.MAX_ANALYSES_PER_SESSION}")
    st.write(f"Questions left: **{config.MAX_CHAT_MESSAGES_PER_SESSION - st.session_state.chat_used}** "
             f"of {config.MAX_CHAT_MESSAGES_PER_SESSION}")
    st.caption("Limits keep this free class project within its API quota.")
    st.subheader("What we check")
    st.markdown("- Security deposits and last month's rent\n- Move-in charges\n- Late fees, entry, repairs, "
                "required disclosures and other tenant protections")
    st.caption("Sources: M.G.L. c. 186 §15B, 940 CMR 3.17, and the Massachusetts Attorney General's "
               "Guide to Landlord and Tenant Rights.")
    with st.expander("Developer options"):
        version = st.selectbox("Prompt version", list(prompts.PROMPTS), index=list(prompts.PROMPTS).index(prompts.ACTIVE_VERSION))
        use_retrieval = st.checkbox("Use retrieval", value=True)
        st.write(f"Model: `{config.MODEL}`")
        st.write(f"Tokens this session: {llm.usage.input_tokens:,} in / {llm.usage.output_tokens:,} out "
                 f"(≈ ${llm.usage.cost_usd:.4f})")


# ---------- upload and analyse ----------

uploaded = st.file_uploader("Upload your lease (text-based PDF or Word .docx)", type=["pdf", "docx"])
run = st.button("Check my lease", type="primary", disabled=uploaded is None)

if run and uploaded is not None:
    if st.session_state.analyses_used >= config.MAX_ANALYSES_PER_SESSION:
        st.error("You have used all the lease checks for this session. Please come back later.")
    else:
        st.session_state.analyses_used += 1  # count attempts, so retries cannot bypass the cap
        bar = st.progress(0.0, text="Reading your lease")
        notice = st.empty()  # shows why we are waiting when the free tier asks us to slow down
        llm.on_wait = lambda message: notice.info(message)

        def show_progress(message: str, fraction: float) -> None:
            notice.empty()
            bar.progress(min(fraction, 1.0), text=message)

        try:
            index = get_index(api_key) if use_retrieval else None
            result = analyze(uploaded.getvalue(), uploaded.name, llm, index, prompt_version=version,
                             progress=show_progress)
            st.session_state.result = result
            st.session_state.filename = uploaded.name
            st.session_state.chat = []
        except InputRejected as exc:
            st.session_state.analyses_used -= 1  # rejected before any model call; don't charge the user
            st.error(exc.message)
        except LLMError as exc:
            st.error(f"Sorry, the check could not finish. {exc}")
        except FileNotFoundError:
            st.error("The app's legal sources are missing. Please tell the team.")
        finally:
            bar.empty()
            notice.empty()
            llm.on_wait = lambda message: None


# ---------- results ----------

result = st.session_state.result
if result is not None:
    st.divider()
    st.subheader(f"Results for {st.session_state.filename}")
    counts = result.counts()
    cols = st.columns(4)
    for col, key in zip(cols, ["possibly_unlawful", "unusual", "lawful", "not_checked"]):
        icon, name = LABEL_STYLE[key]
        col.metric(f"{icon} {name}", counts.get(key, 0))
    if result.parse_failures:
        st.warning(f"{counts.get('not_checked', 0)} clause(s) could not be checked because the model's answer "
                   "was not in the expected format. Try again, or read those clauses yourself.")

    st.markdown("#### Move-in charges")
    check = result.charges.check
    if check:
        st.table([{"Charge": i["charge"], "Amount": f"${i['amount']:,.2f}", "Status": STATUS_STYLE[i["status"]],
                   "Why": i["reason"], "Law": i["citation"]} for i in check["items"]])
        st.caption(f"Monthly rent ${check['monthly_rent']:,.2f}. Most a landlord may collect before move-in "
                   f"(not counting a lock): ${check['maximum_allowed_excluding_lock']:,.2f}.")
    st.write(result.charges.summary)

    st.markdown("#### Clause by clause")
    order = {"possibly_unlawful": 0, "unusual": 1, "not_checked": 2, "lawful": 3}
    show = st.multiselect("Show", list(LABEL_STYLE), default=["possibly_unlawful", "unusual", "not_checked"],
                          format_func=lambda k: f"{LABEL_STYLE[k][0]} {LABEL_STYLE[k][1]}")
    for r in sorted(result.clauses, key=lambda r: (order[r.label], r.clause.clause_id)):
        if r.label not in show:
            continue
        icon, name = LABEL_STYLE[r.label]
        title = r.finding.topic if r.finding else "Clause"
        with st.expander(f"{icon} Clause {r.clause.clause_id}: {title} ({name})",
                         expanded=r.label == "possibly_unlawful"):
            st.markdown(f"> {r.clause.text}")
            if r.finding:
                st.write(r.finding.explanation)
                if r.finding.citation:
                    st.caption(f"Law: {r.finding.citation}")
            else:
                st.write("We could not check this clause. Please read it carefully yourself.")

    # ---------- follow-up chat ----------

    st.divider()
    st.markdown("#### Ask about your lease")
    for turn in st.session_state.chat:
        st.chat_message(turn["role"]).write(turn["content"])
    question = st.chat_input("e.g. Can my landlord keep my deposit for carpet cleaning?")
    if question and question.strip():
        if st.session_state.chat_used >= config.MAX_CHAT_MESSAGES_PER_SESSION:
            st.error("You have used all your questions for this session.")
        else:
            st.session_state.chat_used += 1
            st.chat_message("user").write(question)
            try:
                passages = ""
                if result.used_retrieval:
                    hits = get_index(api_key).search_many(llm, [question], k=4)[0]
                    passages = format_passages([c for c, _ in hits])
                system = prompts.CHAT_SYSTEM.format(findings=findings_digest(result), passages=passages or "(none)")
                answer = llm.chat(system, st.session_state.chat[-10:], question[:2000])
            except LLMError as exc:
                answer = f"Sorry, I could not answer that. {exc}"
            st.session_state.chat += [{"role": "user", "content": question},
                                      {"role": "assistant", "content": answer}]
            st.chat_message("assistant").write(answer)
