# --- Owner: (assign, see docs/TEAM_SPLIT.md) | next steps and the downloadable report ---
# AI-assisted: drafted with Claude Code. The owner must review it and be able to explain it (IS883 §9).
"""Turn an AnalysisResult into things a tenant can act on. Plain code, no model calls: the wording is
templated from the findings, so it costs nothing and cannot invent a new claim."""
from __future__ import annotations

import html
from dataclasses import dataclass
from datetime import date

from .analyzer import AnalysisResult

LABEL_NAMES = {
    "possibly_unlawful": "Possibly unlawful",
    "unusual": "Unusual",
    "lawful": "No issue found",
    "not_checked": "Not checked",
}
SEVERITY = {"possibly_unlawful": 0, "unusual": 1, "not_checked": 2, "lawful": 3}

DISCLAIMER = ("This report was generated by a language model and may be wrong or incomplete. It is not legal "
              "advice. \"No issue found\" does not mean a clause is legal. Check anything important with a "
              "lawyer or a tenant-rights organisation before signing.")

HELP_RESOURCES = [
    ("MassLegalHelp: Housing", "https://www.masslegalhelp.org/housing",
     "Free plain-language guides to Massachusetts tenant rights."),
    ("Greater Boston Legal Services", "https://www.gbls.org/",
     "Free civil legal help for eligible low-income residents."),
    ("Massachusetts Attorney General's Office", "https://www.mass.gov/orgs/office-of-the-attorney-general",
     "Its Consumer Advocacy & Response Division takes questions and complaints about landlords."),
    ("City of Boston Office of Housing Stability", "https://www.boston.gov/departments/housing-stability",
     "Help for Boston renters facing housing problems."),
]


@dataclass
class NextStep:
    severity: str  # "high" | "medium"
    title: str
    detail: str
    citation: str = ""


def next_steps(result: AnalysisResult) -> list[NextStep]:
    """Questions to raise with the landlord, most serious first."""
    steps: list[NextStep] = []
    check = result.charges.check
    if check:
        for item in check["items"]:
            if item["status"] == "not_allowed":
                steps.append(NextStep(
                    "high", f"Ask for the {item['charge'].lower()} (${item['amount']:,.2f}) to be removed or reduced",
                    item["reason"], item["citation"]))
            elif item["status"] == "check":
                steps.append(NextStep(
                    "medium", f"Ask about the {item['charge'].lower()} (${item['amount']:,.2f})",
                    item["reason"], item["citation"]))
    for r in sorted(result.clauses, key=lambda r: (SEVERITY[r.label], r.clause.clause_id)):
        f = r.finding
        if r.label == "possibly_unlawful":
            steps.append(NextStep(
                "high", f"Ask the landlord to remove or rewrite {r.clause.display_name.lower()} ({f.topic})",
                f.explanation, f.citation))
        elif r.label == "unusual":
            steps.append(NextStep(
                "medium", f"Ask why {r.clause.display_name.lower()} ({f.topic}) is there and whether it can change",
                f.explanation))
        elif r.label == "not_checked":
            steps.append(NextStep(
                "medium", f"Read {r.clause.display_name.lower()} yourself",
                "We could not check this clause automatically."))
    return steps


def overall_verdict(result: AnalysisResult) -> tuple[str, str, str]:
    """(tone, headline, sub-line) for the banner at the top of the results."""
    counts = result.counts()
    bad = counts.get("possibly_unlawful", 0)
    charge_problems = (result.charges.check or {}).get("problems_found", 0)
    odd = counts.get("unusual", 0)
    total = len(result.clauses)
    if bad or charge_problems:
        n = bad + charge_problems
        return ("danger", f"{n} item{'s' if n != 1 else ''} may break Massachusetts tenant law",
                f"Raise these with the landlord before you sign. We reviewed {total} clauses.")
    if odd:
        return ("warning", f"No likely violations, but {odd} unusual clause{'s' if odd != 1 else ''}",
                f"Worth asking about before you sign. We reviewed {total} clauses.")
    return ("success", "No likely violations found",
            f"We reviewed {total} clauses. Read the lease carefully anyway: this check is not exhaustive.")


def _e(text: str) -> str:
    return html.escape(text or "")


def html_report(result: AnalysisResult, filename: str) -> str:
    """A self-contained, printable HTML report (open it in a browser and print to PDF)."""
    tone, headline, sub = overall_verdict(result)
    colours = {"danger": "#B42318", "warning": "#B54708", "success": "#067647"}
    pill = {"possibly_unlawful": ("#FEE4E2", "#B42318"), "unusual": ("#FEF0C7", "#B54708"),
            "lawful": ("#DCFAE6", "#067647"), "not_checked": ("#EAECF0", "#475467")}
    counts = result.counts()

    rows = []
    for r in sorted(result.clauses, key=lambda r: (SEVERITY[r.label], r.clause.clause_id)):
        bg, fg = pill[r.label]
        f = r.finding
        rows.append(f"""
        <div class="clause">
          <div class="head"><span class="pill" style="background:{bg};color:{fg}">{LABEL_NAMES[r.label]}</span>
            <strong>{_e(r.clause.display_name)}{(': ' + _e(f.topic)) if f else ''}</strong></div>
          <blockquote>{_e(r.clause.text)}</blockquote>
          {f'<p>{_e(f.explanation)}</p>' if f else '<p>We could not check this clause automatically.</p>'}
          {f'<p class="cite">Law: {_e(f.citation)}</p>' if f and f.citation else ''}
        </div>""")

    charges = ""
    check = result.charges.check
    if check:
        status_text = {"ok": "Allowed", "check": "Check", "not_allowed": "Not allowed"}
        items = "".join(
            f"<tr><td>{_e(i['charge'])}</td><td>${i['amount']:,.2f}</td><td>{status_text[i['status']]}</td>"
            f"<td>{_e(i['reason'])}</td></tr>" for i in check["items"])
        charges = f"""<h2>Move-in charges</h2>
        <table><tr><th>Charge</th><th>Amount</th><th>Status</th><th>Why</th></tr>{items}</table>
        <p class="muted">Monthly rent ${check['monthly_rent']:,.2f}. The most a landlord may collect before move-in
        (excluding a lock) is ${check['maximum_allowed_excluding_lock']:,.2f}.</p>"""

    steps = "".join(f"<li><strong>{_e(s.title)}.</strong> {_e(s.detail)}"
                    f"{(' <span class=muted>(' + _e(s.citation) + ')</span>') if s.citation else ''}</li>"
                    for s in next_steps(result))
    steps_html = f"<h2>Questions to ask your landlord</h2><ol>{steps}</ol>" if steps else ""
    help_html = "".join(f"<li><a href='{u}'>{_e(n)}</a>: {_e(d)}</li>" for n, u, d in HELP_RESOURCES)

    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lease review: {_e(filename)}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color:#101828;
         max-width: 820px; margin: 40px auto; padding: 0 20px; line-height: 1.5; }}
  h1 {{ font-size: 26px; margin-bottom: 4px; }} h2 {{ font-size: 18px; margin-top: 32px; border-bottom:1px solid #EAECF0; padding-bottom:6px; }}
  .muted {{ color:#475467; font-size: 14px; }}
  .verdict {{ border-left: 5px solid {colours[tone]}; background:#F9FAFB; padding: 14px 18px; border-radius: 8px; margin: 20px 0; }}
  .verdict b {{ color:{colours[tone]}; font-size: 18px; }}
  .stats span {{ display:inline-block; margin-right: 18px; font-size: 14px; }}
  .clause {{ border:1px solid #EAECF0; border-radius: 10px; padding: 12px 16px; margin: 12px 0; page-break-inside: avoid; }}
  .pill {{ font-size: 12px; font-weight: 600; padding: 2px 10px; border-radius: 999px; margin-right: 8px; }}
  blockquote {{ margin: 10px 0; padding-left: 12px; border-left: 3px solid #D0D5DD; color:#344054; }}
  .cite {{ font-size: 13px; color:#1F4E79; font-weight: 600; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 14px; }} td, th {{ border-bottom:1px solid #EAECF0; padding: 8px; text-align:left; vertical-align: top; }}
  .disclaimer {{ background:#FFFAEB; border:1px solid #FEDF89; padding: 12px 16px; border-radius: 8px; font-size: 14px; }}
</style></head><body>
<h1>Lease review</h1>
<div class="muted">{_e(filename)} · {date.today().strftime('%B %d, %Y')} · Boston Lease Checker (IS883 student project)</div>
<div class="verdict"><b>{_e(headline)}</b><br>{_e(sub)}</div>
<div class="stats"><span>Possibly unlawful: <b>{counts.get('possibly_unlawful', 0)}</b></span>
<span>Unusual: <b>{counts.get('unusual', 0)}</b></span><span>No issue found: <b>{counts.get('lawful', 0)}</b></span>
<span>Not checked: <b>{counts.get('not_checked', 0)}</b></span></div>
<p class="disclaimer">{_e(DISCLAIMER)}</p>
{steps_html}
{charges}
<h2>Clause by clause</h2>
{''.join(rows)}
<h2>Where to get help</h2><ul>{help_html}</ul>
</body></html>"""
